---
- name: Verify
  hosts: localhost
  tasks:

  - name: Ensure the build directory has been created
    stat:
      path: "./build"
    register: build_directory_check

  - name: Assert that the build directory has been created
    assert:
      that: build_directory_check.stat.exists
  
  - name: Check if the testns-certchain.pem file has been created
    stat:
      path: "./build/testns/testns/testns-certchain.pem"
    register: certchain_pem_check

  - name: Assert if the testns-certchain.pem file has been created
    assert:
      that: certchain_pem_check.stat.exists

  - name: Check if the testns.key file has been created
    stat:
      path: "./build/testns/testns/testns.key"
    register: testns_key_check

  - name: Assert if the testns.key file has been created
    assert:
      that: testns_key_check.stat.exists

  - name: Check if the testns.pem file has been created
    stat:
      path: "./build/testns/testns/testns.pem"
    register: testns_pem_check

  - name: Assert if the testns.pem file has been created
    assert:
      that: testns_pem_check.stat.exists

  - name: Check if the rootca.key file has been created
    stat:
      path: "./build/quorumrootca/rootca.key"
    register: rootca_key_check

  - name: Assert if the rootca.key file has been created
    assert:
      that: rootca_key_check.stat.exists

  - name: Check if the rootca.pem file has been created
    stat:
      path: "./build/quorumrootca/rootca.pem"
    register: rootca_pem_check

  - name: Assert that the rootca.pem file has been created
    assert:
      that: rootca_pem_check.stat.exists
