kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Values.nodeName }}
  {{- if .Values.deployment.annotations }}
    annotations:
{{ toYaml .Values.deployment.annotations | indent 8 }}
  {{- end }}
  namespace: {{ .Values.metadata.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.nodeName }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.nodeName }}
      helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
      app.kubernetes.io/managed-by: {{ .Release.Service }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app: {{ .Values.nodeName }}
  strategy:
    type: Recreate
    rollingUpdate: null
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.nodeName }}
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app: {{ .Values.nodeName }}
    spec:
      hostname: {{ .Values.nodeName }}
      imagePullSecrets:
        - name: {{ .Values.expressapp.pullSecrets | default "regcred" }}
      containers:     
      - name: expressapp
        image: {{ .Values.expressapp.image }}
        imagePullPolicy: {{ .Values.expressapp.pullPolicy }}
        env:
        - name: API_URL
          value: "{{ .Values.expressapp.env.apiUrl }}"
        - name: PORT
          value: "{{ .Values.expressapp.nodePorts.targetPort }}"
        ports:
        - containerPort: {{ .Values.expressapp.nodePorts.targetPort }}
          name: expressapp

