# Default values for nodechart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
# This one is just a demo file, the file to install the helm chart will be created through
# ANSIBLE with the values.tpl file that is in the same folder that this file.

metadata:
  #Provide the namespace for the pod. Use default as Alice is independent and does not belong to an organization
  #Eg. namespace: default
  namespace: default

  #Provide the name for student agent
  #Eg. name: student-alice
  name: student-alice

image:
  agent:
    #Provide the image name for the alice container
    #Eg. name: student-alice
    name: student-alice

    #Provide the image repository for the alice container
    #Eg. repository: sownak/aries-agents:1.11.0
    repository: 

  #Provide the image pull secret of image
  #Eg. pullSecret: regcred
  pullSecret: regcred

service:
    ports:
      #Provide the service node port for service connections
      #Eg. service: 15043
      service: 15043

      #Provide the service node port for swagger UI
      #Eg. endpoint: serviceport+1
      endpoint: 15044

      #Provide the webhook port
      #Eg. webhook: endpointport+1
      webhook: 15045

    #Provide the external address of this agent
    #Eg. address: 192.168.99.204 <minikube ip for minikube>
    #Eg. address: alice.id.demo.aws.blockchaincloudpoc.com <ambassador url when on cluster>
    address:

    #Provide the url for Indy WebServer
    #Eg. ledger: http://192.168.99.204:8000  for minikube
    #Eg. ledger: http://authority-webserver.id.example.blockchaincloudpoc.com:15010 for ambassador
    ledger: 

    #Provide the url for genesis
    #Eg. genesis: http://192.168.99.204:8000/genesis for minikube
    #Eg. genesis: http://authority-webserver.id.example.blockchaincloudpoc.com:15010//genesis for ambassador
    genesis: 

proxy:
  #This will be the proxy provider. Can have values "ambassador" or "minikube"
  # use "minikube" for minikube environment
  #Eg. provider: "ambassador"
  provider: "ambassador"
