#############################################################################################
# This role deletes the helm releases and uninstalls Flux
#############################################################################################

#############################################################################################
# Remove CRD Helmrelease
- name: "Deletes all the helmreleases in {{ component_name }}"
  shell: |
    KUBECONFIG={{ kubernetes.config_file }} kubectl delete --all helmrelease -n "{{ component_name }}"
  ignore_errors: yes
  tags:
    molecule-idempotence-notest
  
# Remove all Helm releases of organization
- name: Remove all Helm releases of namespace {{ component_name }}
  args:
    executable: /bin/bash
  shell: |
    helm_releases=($(KUBECONFIG={{ kubernetes.config_file }} helm ls | grep {{ component_name }} | awk '{print $1}'))
    for helm_release in "${helm_releases[@]}"
    do
      KUBECONFIG={{ kubernetes.config_file }} helm uninstall ${helm_release}
    done
  ignore_errors: yes
  tags:
    molecule-idempotence-notest
  
- name: Deletes namespaces
  k8s:
    kind: Namespace
    name: "{{ component_name }}"
    state: absent
    kubeconfig: "{{ kubernetes.config_file }}"
    context: "{{ kubernetes.context }}"
  ignore_errors: yes
  changed_when: false
