# Get information about each validator node present in network.yaml and store it as a list of org,node
- name: Get node data
  set_fact:
    node_list={{ node_list|default([]) + [ {'org':org.name, 'node':peer.name, 'type':org.type } ] }}
  loop: "{{ org.services.peers }}"
  loop_control:
    loop_var: peer  
