############################################################################################
# Looping on the peers and finding out the peer with a chaincode section
- name: "Deploying the chaincode for peer {{ organization_data.name | lower }}"
  include_tasks: nested_deploy.yaml
  vars:
    smart_contract: "{{ peer.smart_contract }} "
  loop: "{{ organization_data.services.peers }}"
  loop_control:
    loop_var: peer
  when: peer.smart_contract is defined
