# This task checks if the geth binary is already in place or not
- name: Check geth
  stat:
    path: "{{ bin_install_dir }}/geth"
  register: geth_stat_result

  # This task checks if quorum repo directory exists
- name: Check quorum repo dir exists
  stat:
    path: "{{ bin_install_dir }}/quorum"
  register: quorum_stat_result

# This task clones the quorum git repository
- name: Clone the git repo
  git:
    repo: "{{ geth.repo }}"
    version: master
    force: yes
    dest: "{{ bin_install_dir }}/quorum"
  when: not ( quorum_stat_result.stat.exists and geth_stat_result.stat.exists )

# This task builds the geth binary
- name: Make geth
  make:
    chdir: "{{ bin_install_dir }}/quorum"
    target: geth
  when: geth_stat_result.stat.exists == False

# This task creates the bin directory, if it doesn't exist, for storing the geth binary
- name: Create bin directory
  file:
    path: "{{ bin_install_dir }}"
    state: directory
  when: geth_stat_result.stat.exists == False

# This task puts the geth binary to above created bin directory
- name: Copy geth binary to destination directory
  copy:
    src: "{{ bin_install_dir }}/quorum/build/bin/geth"
    dest: "{{ bin_install_dir }}/geth"
    mode: 0755
    remote_src: yes
  when: geth_stat_result.stat.exists == False
