##############################################################################################
# This role creates the value file for doorman
##############################################################################################
    
- name: "Wait for namespace creation for {{ organisation }}"
  include_role:
    name: "{{ playbook_dir }}/../../shared/configuration/roles/check/k8_component"
  vars:
    component_type: "Namespace"
    component_name: "{{ component_ns }}"
    type: "retry"

- name: "Wait for vault-auth creation for {{ organisation }}"
  include_role:
    name: "{{ playbook_dir }}/../../shared/configuration/roles/check/k8_component"
  vars:
    component_type: "ServiceAccount"
    component_name: "vault-auth"
    type: "retry"
  tags:
    - notest    

- name: "Wait for vault-reviewer creation for {{ organisation }}"
  include_role:
    name: "{{ playbook_dir }}/../../shared/configuration/roles/check/k8_component"
  vars:
    component_type: "ServiceAccount"
    component_name: "vault-reviewer"
    type: "retry"
  tags:
    - notest    

- name: "Wait for ClusterRoleBinding creation for {{ organisation }}"
  include_role:
    name: "{{ playbook_dir }}/../../shared/configuration/roles/check/k8_component"
  vars:
    component_type: "ClusterRoleBinding"
    component_name: "{{ component_ns }}-role-tokenreview-binding"
    type: "retry"
  tags:
    - notest    

# ----------------------------------------------------------------------  
# create vault access policies
- name: "Setup vault for doorman"
  include_role: 
    name: setup/vault_kubernetes
  vars:
    component_name: "{{ services.doorman.name | lower }}"
    component_path: "{{ services.doorman.name | lower }}/"
    component_auth: "corda{{ services.doorman.name | lower }}"

# ----------------------------------------------------------------------  
# create image pull secrets
- name: "Create image pull secret for doorman" 
  include_role: 
    name: create/imagepullsecret

# generate Doorman certificates
- name: "Create certificates for doorman" 
  include_role: 
    name: create/certificates/doorman
  vars:
    component_name: "{{ services.doorman.name | lower }}"
    root_subject: "{{ item.subject }}"
    cert_subject: "{{ item.subject | regex_replace(',', '/') }}"
    doorman_subject: "{{ services.doorman.subject }}"
    doorman_cert_subject: "{{ services.doorman.subject | regex_replace(',', '/') }}"
    mongoroot_cert_subj: "{{ services.doorman.db_subject }}"

# Create deployment file for doorman mongodb node when tls is off
- name: "create mongodb for doorman"
  include_role:
    name: create/k8_component
  vars:
    component_name: "doormanmongodb"
    component_type: "mongodb"
    helm_lint: "true"
    nodename: "{{ services.doorman.name }}"
    charts_dir: "{{ gitops.chart_source }}"
    component_auth: "corda{{ services.doorman.name | lower }}"
    org: "{{ item }}"
    release_dir: "{{ playbook_dir }}/../../../{{ gitops.release_dir }}"
    chart: "mongodb"
  when: services.doorman.tls == 'off'

# Create deployment file for doorman mongodb node when tls is on
- name: "create mongodb for doorman"
  include_role:
    name: create/k8_component
  vars:
    component_name: "doormanmongodb"
    component_type: "mongodb"
    helm_lint: "true"
    nodename: "{{ services.doorman.name }}"
    charts_dir: "{{ gitops.chart_source }}"
    component_auth: "corda{{ services.doorman.name | lower }}"
    org: "{{ item }}"
    release_dir: "{{ playbook_dir }}/../../../{{ gitops.release_dir }}"
    chart: "mongodb-tls"
  when: services.doorman.tls == 'on'

# create deployment file for doorman node
- name: "create doorman"
  include_role:
    name: create/k8_component
  vars:
    component_name: "{{ services.doorman.name }}"
    component_type: "doorman"
    helm_lint: "true"
    charts_dir: "{{ gitops.chart_source }}"
    component_auth: "corda{{ services.doorman.name | lower }}"
    org: "{{ item }}"
    release_dir: "{{ playbook_dir }}/../../../{{ gitops.release_dir }}"
    chart: "doorman"
    chart_tls: "false"
  when: services.doorman.tls == 'off'

# create deployment file for doorman node when tls is on
- name: "create doorman"
  include_role:
    name: create/k8_component
  vars:
    component_name: "{{ services.doorman.name }}"
    component_type: "doorman"
    helm_lint: "true"
    charts_dir: "{{ gitops.chart_source }}"
    component_auth: "corda{{ services.doorman.name | lower }}"
    org: "{{ item }}"
    release_dir: "{{ playbook_dir }}/../../../{{ gitops.release_dir }}"
    chart: "doorman-tls"
    chart_tls: "true"
  when: services.doorman.tls == 'on'

# Push the doorman deployment files to repository
- name: "Push the created deployment files to repository"
  include_role: 
    name: "{{ playbook_dir }}/../../shared/configuration/roles/git_push"
  vars:
    GIT_DIR: "{{ playbook_dir }}/../../../"
    GIT_RESET_PATH: "platforms/r3-corda/configuration"
    msg: "[ci skip] Pushing deployment files for doorman node and doorman mongodb node"
  tags:
    - notest
