- name: "Counting Genesis Steward"
  set_fact:
    steward_count={{ steward_count|default(0)|int + 1 }}
  loop: "{{ stewards }}"

- name: Set trustee count to zero
  set_fact:
    trustee_count=0
  
- name: "Counting trustees per Org"
  set_fact:
    trustee_count={{ trustee_count|default(0)|int + 1 }}
    total_trustees={{ total_trustees|default(0)|int + 1 }}
  loop: "{{ trustees }}"

- name: Print error and end playbook if trustee count limit fails
  debug: msg="The trustee count is {{ trustee_count }}. There should be max 1 trustee per organization."
  failed_when: trustee_count|int > 1

- name: "Counting  Endorsers"
  set_fact:
    endorser_count={{ endorser_count|default(0)|int + 1 }}
  loop: "{{ endorsers }}"

- name: Print error abd end playbook  if endorser count limit fails
  debug: msg="The endorser count is {{ endorser_count }}. There should be max 1 endorser per organization."
  failed_when: endorser_count|int > 1
  when: endorser_count is defined

- name: Reset Endorser count
  set_fact:
    endorser_count=0
  when: endorser_count is defined