# This tasks copy the crypto material to the vault
- name: Copy the crypto material to Vault
  shell: |
    vault kv put {{ vault.secret_path | default('secret') }}/{{ component_ns }}/crypto/{{ peer.name }}/data key="$(cat {{ build_path }}/crypto/{{ component_name }}/{{ peer.name }}/data/key)" key_pub="$(cat {{ build_path }}/crypto/{{ component_name }}/{{ peer.name }}/data/key.pub)" nodeAddress="$(cat {{ build_path }}/crypto/{{ component_name }}/{{ peer.name }}/data/nodeAddress)"
  environment:
    VAULT_ADDR: "{{ vault.url }}"
    VAULT_TOKEN: "{{ vault.root_token }}"
  loop: "{{ org.services.peers is defined | ternary(org.services.peers, org.services.validators) }}"
  loop_control:
    loop_var: peer

- name: Copy genesis to Vault
  shell: |
    vault kv put {{ vault.secret_path | default('secret') }}/{{ component_ns }}/crypto/genesis genesis="{{ genesis }}" 
  environment:
    VAULT_ADDR: "{{ vault.url }}"
    VAULT_TOKEN: "{{ vault.root_token }}"
  when: add_new_org is not defined or add_new_org|bool == false
