# This tasks checks for the crypto material to the vault
- name: Check the crypto material in Vault
  shell: |
    vault kv get -format=json {{ vault.secret_path | default('secret') }}/{{ component_ns }}/crypto/{{ item.name }}/data
  environment:
    VAULT_ADDR: "{{ vault.url }}"
    VAULT_TOKEN: "{{ vault.root_token }}"
  with_items: "{{ org.services.peers is defined | ternary(org.services.peers, org.services.validators) }}"
  register: vault_result
  ignore_errors: yes

# This sets a fact vault_result
- set_fact:
    generate_crypto: True
  when: vault_result.failed is defined and vault_result.failed == True
