##############################################################################################
# This role creates the deployment files for node and pushes them to repository
##############################################################################################

- name: "Wait for namespace creation for notary"
  include_role:
    name: "{{ playbook_dir }}/../../shared/configuration/roles/check/k8_component"
  vars:
    component_type: "Namespace"
    component_name: "{{ component_ns }}"
    type: "retry"
  tags:
    - notest

- name: "Wait for vault-auth creation for notary"
  include_role:
    name: "{{ playbook_dir }}/../../shared/configuration/roles/check/k8_component"
  vars:
    component_type: "ServiceAccount"
    component_name: "vault-auth"
    type: "retry"
  tags:
    - notest

- name: "Wait for vault-reviewer creation for notary"
  include_role:
    name: "{{ playbook_dir }}/../../shared/configuration/roles/check/k8_component"
  vars:
    component_type: "ServiceAccount"
    component_name: "vault-reviewer"
    type: "retry"
  tags:
    - notest

- name: "Wait for ClusterRoleBinding creation for notary"
  include_role:
    name: "{{ playbook_dir }}/../../shared/configuration/roles/check/k8_component"
  vars:
    component_type: "ClusterRoleBinding"
    component_name: "{{ component_ns }}-role-tokenreview-binding"
    type: "retry"
  tags:
    - notest

# ----------------------------------------------------------------------  
# create vault access policies
- name: "Setup vault for notaries"
  include_role: 
    name: setup/vault_kubernetes
  vars:
    component_name: "{{ node.name | lower }}"
    component_path: "{{ node.name | lower }}/"
    component_auth: "corda{{ node.name | lower }}"

# ----------------------------------------------------------------------  
# create image pull secrets
- name: "Create image pull secret for notary" 
  include_role: 
    name: create/imagepullsecret

- name: Generate crypto for notary
  include_role:
    name: create/certificates/notary
  vars:
    component_name: "{{ services.notary.name | lower }}"
    nms_url: "{{ network | json_query('network_services[?type==`networkmap`].uri') | first }}"
    nms_cert_file: "{{ network | json_query('network_services[?type==`networkmap`].certificate') | first }}"
    doorman_cert_file: "{{ network | json_query('network_services[?type==`doorman`].certificate') | first }}"
    cordapps_details: "{{ cordapps }}"
    cert_subject: "{{ item.subject | regex_replace(',', '/') }}"  #Use org level subject for certificate generation

# ----------------------------------------------------------------------  
# create deployment files for h2 for notaries
- name: 'Create notary db deployment file'
  include_role:
    name: create/node_component
  vars:    
    node_type: "notary"
    component_type: "db"
    component_name: "{{ node.name }}"
    corda_version: "corda-{{ network.version }}"
    release_dir: "{{ playbook_dir }}/../../../{{ gitops.release_dir }}"

- name: Check if nodekeystore already created
  shell: |
    vault kv get -field=nodekeystore.jks {{ node.name }}/certs/nodekeystore
  environment:
    VAULT_ADDR: "{{ vault.url }}"
    VAULT_TOKEN: "{{ vault.root_token }}"
  register: nodekeystore_result
  ignore_errors: yes
  tags:
    - molecule-idempotence-notest

# ----------------------------------------------------------------------  
# create deployment files for job for notaries
- name: 'Create notary initial-registration job file'
  include_role:
    name: create/node_component
  vars:    
    node_type: "notary"
    component_type: "job"
    component_name: "{{ node.name }}"
    nms_url: "{{ network | json_query('network_services[?type==`networkmap`].uri') | first }}"
    nms_domain: "{{ nms_url.split(':')[1] }}"
    doorman_url: "{{ network | json_query('network_services[?type==`doorman`].uri') | first }}"
    doorman_domain: "{{ doorman_url.split(':')[1] }}"
    corda_version: "corda-{{ network.version }}"
    release_dir: "{{ playbook_dir }}/../../../{{ gitops.release_dir }}"
  when: nodekeystore_result.failed == True

- name: "Push the created deployment files to repository"
  include_role: 
    name: "{{ playbook_dir }}/../../shared/configuration/roles/git_push"
  vars:
    GIT_DIR: "{{ playbook_dir }}/../../../"
    GIT_RESET_PATH: "platforms/r3-corda/configuration"
    msg: "[ci skip] Pushing db and job deployment files for {{ node.name }}"

#----------------------------------------------------------------------  
# create deployment file for notary node
- name: 'Create notary node deployment file'
  include_role: 
    name: create/node_component
  vars:    
    node_type: "notary"
    component_type: "node"
    component_name: "{{ node.name }}"
    nms_url: "{{ network | json_query('network_services[?type==`networkmap`].uri') | first }}"
    nms_domain: "{{ nms_url.split(':')[1] }}"
    doorman_url: "{{ network | json_query('network_services[?type==`doorman`].uri') | first }}"
    doorman_domain: "{{ doorman_url.split(':')[1] }}"
    corda_version: "corda-{{ network.version }}"
    cordapps_details: "{{ cordapps }}" 
    release_dir: "{{ playbook_dir }}/../../../{{ gitops.release_dir }}"

# ----------------------------------------------------------------------  
# Push the deployment files for notary node
- name: 'Push notary deployment files'
  include_role: 
    name: "{{ playbook_dir }}/../../shared/configuration/roles/git_push"
  vars:
    GIT_DIR: "{{ playbook_dir }}/../../../"
    GIT_RESET_PATH: "platforms/r3-corda/configuration"
    msg: "[ci skip] Pushing notary deployment file for {{ node.name }}"
