##########################################################################################
# This role creates the docker pull registry secret within each namespace
##########################################################################################
- name: "Check for ImagePullSecret for {{ organisation }}"
  include_role:
    name: "{{ playbook_dir }}/../../shared/configuration/roles/check/setup"
  vars:
    component_name: "{{ component_ns }}"
    check: "docker_credentials"
  
- name: Setting the docker cred check task output to the local variable
  set_fact:
    secret_present: "{{ get_regcred }}"

- name: Create the docker pull registry secret for {{ component_ns }}
  shell: |
    KUBECONFIG={{ kubernetes.config_file }} kubectl create secret -n {{ component_ns }} docker-registry regcred --docker-server={{ network.docker.url }} --docker-username={{ network.docker.username }} --docker-password={{ network.docker.password }} --docker-email="test@abc.mail"
  when: secret_present.resources|length == 0
  changed_when: false
