- name: "Check if Indy nodes are running"
  include_role:
    name: "{{ playbook_dir }}/../../../platforms/shared/configuration/roles/check/helm_component"
  vars:
    namespace: "{{ component_ns }}"
    component_name: "{{ organization.name }}-{{ steward.name }}-node"
    component_type: "Pod"
    label_selectors:
      - app = {{ component_name }}
  loop: "{{ services.stewards }}"
  loop_control:
    loop_var: steward
  when: services.stewards is defined

- name: "Create Indy WebServer value file"
  include_role:
    name: create/helm_component
  vars:
    type: "webserver"
    charts_dir: "examples/identity-app/charts"
    component_name: "{{ organization.name }}-{{ type }}"
    component_port: "{{ trustee.server.port }}"
    trustee_name: "{{ trustee.name }}"
    service_account: "{{ organization.name }}-{{ trustee_name }}-vault-auth"
    auth_method_path: "kubernetes-{{ organization.name }}-{{ trustee_name }}-auth"
  loop: "{{ services.trustees }}"
  loop_control:
    loop_var: trustee
  when: 
  - services.trustees is defined
  - trustee.server is defined

- name: "Set Variable"
  set_fact:
   trustee_url: "http://{{ minikube_ip }}:{{ trustee.server.ambassador }}"
  loop: "{{ services.trustees }}"
  loop_control:
    loop_var: trustee
  when: 
  - services.trustees is defined
  - trustee.server is defined
  - organization.cloud_provider == 'minikube'

- name: "Set Variable"
  set_fact:
   trustee_url: "http://{{ organization.name }}-webserver.{{ organization.external_url_suffix }}:{{ trustee.server.ambassador }}"
  loop: "{{ services.trustees }}"
  loop_control:
    loop_var: trustee
  when: 
  - services.trustees is defined
  - trustee.server is defined
  - organization.cloud_provider != 'minikube'

- name: "Push the created deployment files to repository"
  include_role:
    name: "{{ playbook_dir }}/../../../platforms/shared/configuration/roles/git_push"
  vars:
    GIT_DIR: "{{ playbook_dir }}/../../../"
    GIT_RESET_PATH: "platforms/hyperledger-indy/configuration"
    msg: "[ci skip] Pushing deployment files for indy webserver"
  loop: "{{ services.trustees }}"
  loop_control:
    loop_var: trustee
  when: 
  - services.trustees is defined
  - trustee.server is defined

- name: "Wait until Indy WebServer will be up"
  include_role:
    name: "{{ playbook_dir }}/../../../platforms/shared/configuration/roles/check/helm_component"
  vars:
    namespace: "{{ component_ns }}"
    component_type: "Pod"
    component_name: "{{ organization.name }}-webserver"
    label_selectors:
      - app = {{ component_name }}
  loop: "{{ services.trustees }}"
  loop_control:
    loop_var: trustee
  when: 
  - services.trustees is defined
  - trustee.server is defined  
