# This role creates the node DB and registration pods
---
- name: Create Node DB and initial-registration files
  include_tasks: nested_main.yaml
  vars:
    node_name: "{{ peer.name | lower }}"
  loop: "{{ org.services.peers }}"
  loop_control:
    loop_var: peer
