{{- if eq .Values.proxy.provider "haproxy" }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.node.name }}
  namespace: {{ .Values.metadata.namespace }}
  annotations:
    kubernetes.io/ingress.class: "haproxy"
    ingress.kubernetes.io/ssl-passthrough: "true"  
spec:
  rules:
  - host: {{ .Values.node.name }}tm.{{ .Values.proxy.external_url }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Values.node.name }}
          servicePort: {{ .Values.node.ports.tm }}
  - host: {{ .Values.node.name }}rpc.{{ .Values.proxy.external_url }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Values.node.name }}
          servicePort: {{ .Values.node.ports.rpc }}
  - host: {{ .Values.node.name }}tcp.{{ .Values.proxy.external_url }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Values.node.name }}
          servicePort: {{ .Values.node.ports.quorum }}
  {{- if eq $.Values.node.consensus "raft" }}
  - host: {{ .Values.node.name }}raft.{{ .Values.proxy.external_url }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Values.node.name }}
          servicePort: {{ .Values.node.ports.raft }}
  {{- end }}
{{- end }}
