# This task creates the node address for each peer 
- name: Generate the nodeAddress for each peer
  shell: |
    {{ bin_install_dir }}/besu/besu-{{ network.version }}/besu --data-path {{ build_path }}/crypto/{{item[1].org}}/{{item[1].node}}/data public-key export-address --to {{ build_path }}/crypto/{{item[1].org}}/{{item[1].node}}/data/nodeAddress
  with_indexed_items: "{{ enode_validator_list }}"

# This task creates the node public key for new validator
- name: Generate the key.pub for new validator
  shell: |
    {{ bin_install_dir }}/besu/besu-{{ network.version }}/besu --data-path {{ build_path }}/crypto/{{item[1].org}}/{{item[1].node}}/data public-key export --to {{ build_path }}/crypto/{{item[1].org}}/{{item[1].node}}/data/key.pub
  with_indexed_items: "{{ enode_validator_list }}"
