helm_templates:
  pki-generator: pki-generator.tpl
  pki-generator-node: pki-generator-node.tpl
  signer: signer.tpl
  idman: idman.tpl
  nmap: nmap.tpl
  notary-initial-registration: notary_initial_registration.tpl
  db: db.tpl
  notary: notary.tpl
  bridge: bridge.tpl
  float: float.tpl
  node_registration: node_registration.tpl
  node: node.tpl
docker_images:
  cenm:
    pki-1.2: corda/enterprise-pki:1.2-zulu-openjdk8u242
    pki-1.5: corda/enterprise-pki:1.5.1-zulu-openjdk8u242
    signer-1.2: corda/enterprise-signer:1.2-zulu-openjdk8u242
    signer-1.5: corda/enterprise-signer:1.5.1-zulu-openjdk8u242
    networkmap-1.2: corda/enterprise-networkmap:1.2-zulu-openjdk8u242
    networkmap-1.5: corda/enterprise-networkmap:1.5.1-zulu-openjdk8u242
    idman-1.2: corda/enterprise-identitymanager:1.2-zulu-openjdk8u242
    idman-1.5: corda/enterprise-identitymanager:1.5.1-zulu-openjdk8u242
    notary-4.4: corda/enterprise-node:4.4
    notary-4.7: corda/enterprise-node:4.7
    firewall-4.4: corda/enterprise-firewall:4.4
    node-4.4: corda/enterprise-node:4.4
    node-4.7: corda/enterprise-node:4.7
  init_container: alpine-utils:1.0
