############################################################################################
- name: "Check or Wait for node pod to be up"
  include_role:
    name: "{{ playbook_dir }}/../../../platforms/shared/configuration/roles/check/helm_component"
  vars:
    component_type: "Pod"
    namespace: "{{ component_ns }}"
    component_name: "{{ node.name | lower }}"
    kubernetes: "{{ organization_data.k8s }}"
    label_selectors:
      - app = {{ component_name }}
  loop: "{{ organization_data.services.peers }}"
  loop_control:
    loop_var: node
  when: node.springboot is defined

# Create corda webserver value file for the peer nodes
- name: "Create webserver values file for peer organizations"
  include_role:
    name: helm_component
  vars:
    type: "webserver"
    platform_type: "cordaopensource"
    name: "{{ node.name }}"
    charts_dir: "{{ organization_data.gitops.chart_source }}"
    image_tag: "{{ springboot_image_tag[network.version] }}"
    networkmap_name: na
    doorman_name: na
  loop: "{{ organization_data.services.peers }}"
  loop_control:
    loop_var: node
  when: node.springboot is defined and network['type'] == 'corda'

# Create corda webserver value file for the peer nodes
- name: "Create webserver values file for peer organizations"
  include_role:
    name: helm_component
  vars:
    type: "webserver-ent"
    platform_type: "cordaenterprise"
    component_ns: "{{ organization_data.name | lower }}-ent"
    name: "{{ node.name }}"
    charts_dir: "{{ organization_data.gitops.chart_source }}"
    image_tag: "{{ springboot_image_tag[network.version] }}"
    networkmap_name: "{{ network | json_query('network_services[?type==`networkmap`].name') | first }}"
    doorman_name: "{{ network | json_query('network_services[?type==`idman`].name') | first }}"
  loop: "{{ organization_data.services.peers }}"
  loop_control:
    loop_var: node
  when: node.springboot is defined and network['type'] == 'corda-enterprise'

# Push the webserver deployment files to repository
- name: "Push the created deployment files to repository"
  include_role: 
    name: "{{ playbook_dir }}/../../../platforms/shared/configuration/roles/git_push"
  vars:
    GIT_DIR: "{{ playbook_dir }}/../../../"
    gitops: "{{ component_gitops }}"
    GIT_RESET_PATH: "platforms/r3-corda/configuration"
    msg: "[ci skip] Pushing deployment files for corda webserver"
