############################################################################################
# Create restserver value file for the peer nodes
- name: "Create restserver values file for peer organizations"
  include_role:
    name: helm_component
  vars:
    type: "restserver"
    name: "{{ organization_data.name | lower }}"
    charts_dir: "{{ organization_data.gitops.chart_source }}"
    peer_name: "{{ peer_data.name }}"
    peer_restserver_port: "{{ peer_data.restserver.port }}"
    peer_restserver_targetport: "{{ peer_data.restserver.targetPort }}"
    peer_url: "{{ peer_data.gossippeeraddress }}"
    orderer_url: "{{ network | json_query('orderers[?type==`orderer`].uri') | first }}"
  loop: "{{ organization_data.services.peers }}"
  loop_control:
    loop_var: peer_data
  when: component_type == 'peer' and peer_data.restserver is defined

# Push the restserver deployment files to repository
- name: "Push the created deployment files to repository"
  include_role: 
    name: "{{ playbook_dir }}/../../../platforms/shared/configuration/roles/git_push"
  vars:
    GIT_DIR: "{{ playbook_dir }}/../../../"
    gitops: "{{ component_gitops }}"
    GIT_RESET_PATH: "platforms/hyperledger-fabric/configuration"
    msg: "[ci skip] Pushing deployment files for fabric restserver"
  when: component_type == 'peer'