---
- name: Verify
  hosts: localhost
  tasks:

  - name: Ensure the build directory has been created
    stat:
      path: "./build"
    register: build_directory_check

  - name: Assert that the build directory has been created
    assert:
      that: build_directory_check.stat.exists

  - name: Check if the tm.key file has been created
    stat:
      path: "./build/warehouse/warehouse/tm.key"
    register: tm_key_check

  - name: Assert that the tm.key file has been created
    assert:
      that: tm_key_check.stat.exists

  - name: Check if the tessera-app.jar file exists
    stat:
      path: "./build/tessera-app.jar"
    register: tessera_app_jar_check

  - name: Assert that the tessera-app.jar file exists
    assert:
      that: tessera_app_jar_check.stat.exists
