# Call credential tasks for org type as cenm
- name: Call cenm_tasks.yaml for org as type cenm
  include_tasks: cenm_tasks.yaml
  when: org.type == 'cenm'

# Call credential tasks for org type as node
- name: Call node_tasks.yaml for org as type node
  include_tasks: node_tasks.yaml
  when: org.type == 'node'
