
# This task checks if the crypto material is already stored in the vault or not
- name: Check the crypto material in Vault
  shell: |
    vault read -field=db_user {{ vault.secret_path | default('secret') }}/{{ component_ns }}/crypto/{{ item.name }}/credentials
  environment:
    VAULT_ADDR: "{{ vault.url }}"
    VAULT_TOKEN: "{{ vault.root_token }}"
  register: vault_cred_result
  ignore_errors: yes
  tags:
    molecule-idempotence-notest

# This tasks copy the crypto material to the vault
- name: Copy the crypto material to Vault
  shell: |
    vault kv put {{ vault.secret_path | default('secret') }}/{{ component_ns }}/crypto/{{ item.name }}/credentials db_user="demouser" db_password="password" gethpassword="{{ item.geth_passphrase }}"
  environment:
    VAULT_ADDR: "{{ vault.url }}"
    VAULT_TOKEN: "{{ vault.root_token }}"
  when: vault_cred_result.failed == True
  tags:
    molecule-idempotence-notest
