---
# Task to transfer did and seed vaules from one secret engine to another

# Transfer DID and Seed Values between Vaults
- name: "Transfer DID and Seed Values between Vaults"
  shell: |
    new_org={{ organization }}
    new_org_role="stewards";
    new_org_alias={{ stewardItem.name }}

    trustee_seed=$(curl --header "X-Vault-Token: {{ vault.root_token }}" {{ vault.url }}/v1/$new_org/trustees/$new_org-trustee/identity/private | jq -j ".data.seed")
    trustee_did=$(curl --header "X-Vault-Token: {{ vault.root_token }}" {{ vault.url }}/v1/$new_org/trustees/$new_org-trustee/identity/public | jq -j ".data.did")
    trustee_verkey=$(curl --header "X-Vault-Token: {{ vault.root_token }}" {{ vault.url }}/v1/$new_org/trustees/$new_org-trustee/node/public/verif_keys | jq -j ".data.\"verification-key\"")
      
    curl -X POST --header "X-Vault-Token: {{ vault.root_token }}" --header "Content-Type: application/json" -d '{"seed": "'"$trustee_seed"'"}' {{ vault.url }}/v1/$new_org/$new_org_role/$new_org_alias/trustee/private    
    curl -X POST --header "X-Vault-Token: {{ vault.root_token }}" --header "Content-Type: application/json" -d '{"did": "'"$trustee_did"'"}' {{ vault.url }}/v1/$new_org/$new_org_role/$new_org_alias/trustee/public
    curl -X POST --header "X-Vault-Token: {{ vault.root_token }}" --header "Content-Type: application/json" -d '{"verkey": "'"$trustee_verkey"'"}' {{ vault.url }}/v1/$new_org/$new_org_role/$new_org_alias/trustee/node
    
  loop: "{{ services.stewards }}"
  when: services.stewards is defined
  loop_control:
    loop_var: stewardItem

    
