apiVersion: v1
kind: ConfigMap
metadata:
  name: fabric-config
  namespace: {{ .Values.metadata.namespace }}
data:
  fabric-connection.yaml: |
    name: "baf.fabric.supplychain"
    x-type: "hlfv1"
    description: "Connection profile for Supplychain App"
    version: "1.0"
    client:
      organization: {{ .Values.server.localmspid }}
      connection:
        timeout:
            peer:
              endorser: "300"
              eventHub: "300"
              eventReg: "300"
            orderer: "300"

    channels:
      allchannel:
        orderers:
          - {{ .Values.connection.ordererAddress }}
        peers:
          {{ .Values.connection.peer }}:
            endorsingPeer: true
            chaincodeQuery: true
            ledgerQuery: true
            eventSource: true
            discover: true

    organizations:
      {{ .Values.server.localmspid }}:
        mspid: {{ .Values.server.localmspid }}
        peers:
          - {{ .Values.connection.peer }}

    orderers:
      {{ .Values.connection.ordererAddress }}:
        url: grpcs://{{ .Values.connection.ordererAddress }}:{{ .Values.connection.ordererPort }}
        grpcOptions:
          ssl-target-name-override: {{ .Values.connection.ordererAddress }}
          grpc.keepalive_time_ms: 6000
          request-timeout: 12000000
        tlsCACerts:
          path: /secret/msp/tlscacerts/orderer-tlsca.pem

    peers:
      {{ .Values.connection.peer }}:
        url: grpcs://{{ .Values.connection.peerAddress }}:{{ .Values.connection.peerPort }}
        grpcOptions:
          ssl-target-name-override: {{ .Values.connection.peerAddress }}
          grpc.keepalive_time_ms: 6000
          request-timeout: 1200000
        tlsCACerts:
          path: /secret/msp/tlscacerts/tlsca.pem
