apiVersion: v1
kind: Service
metadata:
  name: {{ $.Values.server.name }}
  namespace: {{ $.Values.metadata.namespace }}
  labels:
    run: {{ $.Values.server.name }}
    app.kubernetes.io/name: {{ $.Values.server.name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }} 
spec:
  type: {{ $.Values.service.servicetype }}
  selector:
    app: {{ $.Values.server.name }}
  ports:
  - name: http-port
    protocol: TCP
    port: {{ $.Values.service.ports.apiPort }}
    targetPort: {{ $.Values.service.ports.targetPort }}
