apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $.Values.server.name }}-pvc
  namespace: {{ $.Values.metadata.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.server.name }}-pvc
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }} 
spec:
  storageClassName: {{ $.Values.storage.storageclassname }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $.Values.storage.storagesize }}