version: '2'

services:
  notary:
    image: 895052373684.dkr.ecr.eu-west-1.amazonaws.com/supplychain_node_notary:34
    container_name: notary
    restart: always
    networks:
      - "corda_network"
    environment:
      CONTROLLER_NODE: "true"
      CITY: "London"
      COUNTRY: "GB"
      P2P_ADDRESS: "notary"
      RPC_ADDRESS: "notary"
      SERVICE_NAME: "notary"
    ports:
      - "10002-10003:10002-10003"
      - "10043:10043"
    expose:
      - "10002-10090"
      - "80"
      - "443"
    
  PartyA:
    image: 895052373684.dkr.ecr.eu-west-1.amazonaws.com/supplychain_node_PartyA:34
    container_name: PartyA
    restart: always
    networks:
      - "corda_network"
    environment:
      CONTROLLER_NODE: "false"
      NETWORK_MAP_SERVICE: "PartyA"
      CITY: "London"
      COUNTRY: "GB"
      P2P_ADDRESS: "PartyA"
      RPC_ADDRESS: "PartyA"
      WEB_ADDRESS: "PartyA"
      SERVICE_NAME: "PartyA"
    ports:
      - "10005:10005"
      - "10046:10046"
    expose:
      - "10002-10090"
      - "80"
      - "443"
      - "20005"
    depends_on:
      - notary 
      
  PartyB:
    image: 895052373684.dkr.ecr.eu-west-1.amazonaws.com/supplychain_node_PartyB:34
    container_name: PartyB
    restart: always
    networks:
      - "corda_network"
    environment:
      CONTROLLER_NODE: "false"
      NETWORK_MAP_SERVICE: "PartyB"
      CITY: "New York"
      COUNTRY: "US"
      P2P_ADDRESS: "PartyB"
      RPC_ADDRESS: "PartyB"
      WEB_ADDRESS: "PartyB"
      SERVICE_NAME: "PartyB"
    ports:
      - "10008:10008"
      - "10049:10049"
    expose:
      - "10002-10090"
      - "80"
      - "443"
      - "20008"
    depends_on:
      - notary
      
networks:
  corda_network:
    external:
      name: corda_network
