kernel:
  image: linuxkit/kernel:4.19.34
  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0"
init:
  - linuxkit/init:v0.7
  - linuxkit/runc:v0.7
  - linuxkit/containerd:v0.7
  - linuxkit/ca-certificates:v0.7
  - hyperledgerlabs/linuxkit-java:latest
onboot:
  - name: sysctl
    image: linuxkit/sysctl:v0.7
  - name: dhcpcd
    image: linuxkit/dhcpcd:v0.7
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
  - name: metadata
    image: linuxkit/metadata:v0.7
services:
  - name: rngd
    image: linuxkit/rngd:v0.7
