#############################################################################################
# This role deletes the helm releases and uninstalls Flux
#############################################################################################

# Remove CRD Helmrelease
- name: "Deletes all the helmreleases in {{ component_ns }}"
  shell: |
    KUBECONFIG={{ k8s.config_file }} kubectl delete --all helmrelease -n "{{ component_ns }}"
  ignore_errors: yes

# Remove all Helm releases of organization
- name: Remove all Helm releases of namespace {{ org.name | lower }}
  args:
    executable: /bin/bash
  shell: |
    helm_releases=($(KUBECONFIG={{ k8s.config_file }} helm ls -A | grep {{ org.name | lower }} | awk '{print $1}'))
    for helm_release in "${helm_releases[@]}"
    do
      KUBECONFIG={{ k8s.config_file }} helm uninstall ${helm_release}
    done
  ignore_errors: yes
  
- name: Deletes namespaces
  k8s:
    kind: Namespace
    name: "{{ component_ns }}"
    state: absent
    kubeconfig: "{{ k8s.config_file }}"
    context: "{{ k8s.context }}"
  ignore_errors: yes
