# This role calls for pushing tlscerts to vault for each node
---
- name: Push tls certficates to vault
  include_tasks: nested_main.yaml
  loop: "{{ org.services.peers }}"
  loop_control:
    loop_var: peer
