kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.nodeName }}
  namespace: {{ .Values.metadata.namespace }}
  {{- if eq $.Values.proxy.provider "ambassador" }}
  annotations:
    getambassador.io/config: | 
      ---
      apiVersion: ambassador/v2
      kind: TLSContext
      name: {{ .Values.proxy.peer_name }}_web_context
      hosts:
      - {{ .Values.proxy.peer_name }}web.{{ .Values.proxy.external_url_suffix }}
      secret: {{ .Values.proxy.ambassador_secret }}.default
      secret_namespacing: true
      ---
      apiVersion: ambassador/v2
      kind: Mapping
      name: {{ .Values.proxy.peer_name }}_web_p2p_mapping
      prefix: /
      host: {{ .Values.proxy.peer_name }}web.{{ .Values.proxy.external_url_suffix }}
      service: {{ .Values.proxy.peer_name }}-frontend.{{ .Values.metadata.namespace }}:{{ .Values.frontend.nodePorts.port }}
      tls: false
  {{ end }}
  labels:
    run: {{ .Values.nodeName }}
    app.kubernetes.io/name: {{ .Values.nodeName }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.frontend.serviceType }}
  selector:
    app: {{ .Values.nodeName }}
  ports:
  - port: {{ .Values.frontend.nodePorts.port }}
    targetPort: {{ .Values.frontend.nodePorts.targetPort }}
    protocol: TCP
        
{{- if eq $.Values.proxy.provider "haproxy" }}
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.nodeName }}
  namespace:  {{ $.Values.metadata.namespace }}
  annotations:
    kubernetes.io/ingress.class: "haproxy"
spec:
  tls:
  - hosts:
    - {{ .Values.proxy.peer_name }}web.{{ .Values.proxy.external_url_suffix }}
    secretName: {{ .Values.proxy.ambassador_secret }}
  rules:
  - host: {{ .Values.proxy.peer_name }}web.{{ .Values.proxy.external_url_suffix }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Values.proxy.peer_name }}-frontend
          servicePort: {{ .Values.frontend.nodePorts.port }}
{{- end }}
