---
tmp_directory: "{{ lookup('env', 'TMPDIR') | default('/tmp',true) }}"
release_version: "1604"
constellation:
  repo: https://github.com/ConsenSys/constellation/releases/download/v{{version}}/constellation-{{version}}-ubuntu{{release_version}}.tar.xz
