# Default values for nodechart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
# This one is just a demo file, the file to install the helm chart will be created through
# ANSIBLE with the values.tpl file that is in the same folder that this file. 

# This will be the name of the node to create
nodeName: 
metadata:
  namespace: 

# The number of replicas the node will have
replicaCount: 1

deployment:
  #   annotations:
  #     key: "value"
  annotations: {}

# This will group the values of the expressapp
expressapp:
  #This defines the service type of the node, it will always be NodePort for the expressapp
  serviceType: 
  # The image that will be pulled from docker url
  image: 
  # The pull policy
  pullPolicy: Always
  # The node ports to be used
  pullSecrets: regcred
  nodePorts:
      port: 3000
      targetPort: 3000
      name: 
  # The environment variables that will store the port to be working on and the end point to ask for requests
  #Eg. apiUrl: api.blockchaincloudpoc.com
  env:
    apiUrl: 
proxy:
  #This will be the proxy/ingress provider. Can have values "ambassador" or "haproxy"
  #Eg. provider: "haproxy"
  provider: 
  #This will be the name of the organization
  #Eg. name: carrier
  name: 
  #Type can be fabric/corda
  #Eg. type: fabric
  type: test
  #External URL of the organization
  #Eg. external_url_suffix: org1.blockchaincloudpoc.com
  external_url_suffix: 
  #Name of the peer
  #Eg. peer_name: peer0
  peer_name: 
