#########################
# Playbook to create deployment files for namespaces, service account and clusterrolebinding
# Playbook arguments: complete network.yaml
#########################
- hosts: ansible_provisioners
  gather_facts: no
  no_log: "{{ no_ansible_log | default(false) }}"
  tasks:
  # clean build directory
  - name: Remove build directory
    file:
      path: "./build"
      state: absent
  
  # Validate input network.yaml
  - name: "Validating network.yaml"
    include_role:
      name: check/validation

  # Create namespaces for organizations
  - name: 'Create namespace'
    include_role:
      name: create/namespace
    vars:
      component_name: "{{ organizationItem.name | lower }}-ns"
      component_type_name: "{{ organizationItem.type | lower }}"
      kubernetes: "{{ organizationItem.k8s }}"
      release_dir: "{{playbook_dir}}/../../../{{organizationItem.gitops.release_dir}}/{{ organizationItem.name | lower }}"
    loop: "{{ network['organizations'] }}"
    loop_control:
      loop_var: organizationItem
    when: organizationItem.org_status is not defined or organizationItem.org_status == 'new'

  # Create service accounts
  - name: 'Create service accounts'
    include_role:
      name: create/serviceaccount/main
    vars:
      component_ns: "{{ organizationItem.name | lower }}-ns"
      organization: "{{ organizationItem.name | lower }}"
      component_type_name: "{{ organization }}"
      services: "{{ organizationItem.services }}"
      gitops: "{{ organizationItem.gitops }}"
      kubernetes: "{{ organizationItem.k8s }}"
    loop: "{{ network['organizations'] }}"
    loop_control:
      loop_var: organizationItem
    when: organizationItem.org_status is not defined or organizationItem.org_status == 'new'

  # Create StorageClass
  - name: Create Storage Class
    include_role:
      name: create/storageclass
    vars:
      organization: "{{ organizationItem.name | lower }}"
      component_ns: "{{ organizationItem.name | lower }}-ns"
      provider: "{{ organizationItem.cloud_provider }}"
      storageclass_name: "{{ provider }}-storageclass"
      component_name: "{{ organization }}-{{ storageclass_name }}"
      gitops: "{{ organizationItem.gitops }}"
      kubernetes: "{{ organizationItem.k8s }}"
      aws: "{{ organizationItem.aws }}"
    loop: "{{ network['organizations'] }}"
    loop_control:
      loop_var: organizationItem
    when: organizationItem.org_status is not defined or organizationItem.org_status == 'new'

  # Admin K8S auth
  - name: Admin K8S auth
    include_role:
      name: setup/vault_kubernetes
    vars:
      organization: "{{ organizationItem.name | lower }}"
      component_ns: "{{ organizationItem.name | lower }}-ns"
      component_name: "{{ organization }}-baf-ac-vault-auth"
      component_type: "GetServiceAccount"
      vault: "{{ organizationItem.vault }}"
      auth_path: "kubernetes-{{ organization }}-admin-auth"
      kubernetes: "{{ organizationItem.k8s }}"
    loop: "{{ network['organizations'] }}"
    loop_control:
      loop_var: organizationItem
    when: organizationItem.org_status is not defined or organizationItem.org_status == 'new'

  # Generate auth job
  - name: 'Generate auth job'
    include_role:
      name: setup/auth_job
    vars:
      organization: "{{ organizationItem.name | lower }}"
      component_ns: "{{ organizationItem.name | lower }}-ns"
      component_name: "{{ organization }}"
      services: "{{ organizationItem.services }}"
      kubernetes: "{{ organizationItem.k8s }}"
      vault: "{{ organizationItem.vault }}"
      gitops: "{{ organizationItem.gitops }}"
    loop: "{{ network['organizations'] }}"
    loop_control:
      loop_var: organizationItem
    when: organizationItem.org_status is not defined or organizationItem.org_status == 'new'

  # Get Vault AC Token via Service Account
  - name: Get Vault AC Token via Service Account
    include_role:
      name: check/k8_component
    vars:
      organization: "{{ organizationItem.name | lower }}"
      component_ns: "{{ organizationItem.name | lower }}-ns"
      component_name: "{{ organization }}-baf-ac-vault-auth"
      component_type: "GetServiceAccount"
      vault: "{{ organizationItem.vault }}"
      kubernetes: "{{ organizationItem.k8s }}"
    loop: "{{ network['organizations'] }}"
    loop_control:
      loop_var: organizationItem   

  # Generate indy crypto and insert into Vault
  - name: 'Generate indy crypto and insert into Vault'
    include_role:
      name: setup/crypto
    vars:
      organization: "{{ organizationItem.name | lower }}"
      component_ns: "{{ organizationItem.name | lower }}-ns"
      component_name: "{{ organization }}"
      services: "{{ organizationItem.services }}"
      kubernetes: "{{ organizationItem.k8s }}"
      vault: "{{ organizationItem.vault }}"
      gitops: "{{ organizationItem.gitops }}"
      vault_ac_token: "{{ ac_vault_tokens[organization] }}"
    loop: "{{ network['organizations'] }}"
    loop_control:
      loop_var: organizationItem
    when: organizationItem.org_status is not defined or organizationItem.org_status == 'new'

  # Create and deploy domain genesis
  - name: 'Create domain genesis'
    include_role:
      name: setup/domain_genesis

  # Create and deploy pool genesis
  - name: 'Create pool genesis'
    include_role:
      name: setup/pool_genesis

  # Add new trustee from existing trustee
  - name: "Add New Trustee Node via existing Trustee"
    include_role:
      name: setup/trustee
    vars:
      new_org_query: "organizations[?org_status=='new']"
      neworg: "{{ network | json_query(new_org_query) | first }}"
      organization: "{{ organizationItem.name | lower }}"
      component_ns: "{{ organizationItem.name | lower }}-ns"
      component_name: "{{ organization }}"      
      kubernetes: "{{ organizationItem.k8s }}"
      gitops: "{{ organizationItem.gitops }}"  
      vault: "{{ organizationItem.vault }}"
      genesis: "{{ network.genesis }}"
    loop: "{{ network['organizations'] }}"
    loop_control:
      loop_var: organizationItem
    when:
    - network.genesis.add_org is defined and network.genesis.add_org    
    - organizationItem.org_status is not defined or organizationItem.org_status == 'existing'
  
  # Transfer DID and Seed Values between Vaults
  - name: "Transfer DID and Seed Values from trustee to steward"
    include_role:
      name: copy/vault_crypto_values
    vars:
      organization: "{{ organizationItem.name | lower }}"
      component_ns: "{{ organizationItem.name | lower }}-ns"
      component_name: "{{ organization }}"
      services: "{{ organizationItem.services }}"
      vault: "{{ organizationItem.vault }}"
    loop: "{{ network['organizations'] }}"
    loop_control:
      loop_var: organizationItem
    when:
    - network.genesis.add_org is defined and network.genesis.add_org    
    - organizationItem.org_status is not defined or organizationItem.org_status == 'new'
    - organizationItem.type == 'peer'

  # Deploy all other nodes
  - name: 'Deploy nodes'
    include_role:
      name: setup/node
    vars:
      organization: "{{ organizationItem.name | lower }}"
      component_ns: "{{ organizationItem.name | lower }}-ns"
      services: "{{ organizationItem.services }}"
      kubernetes: "{{ organizationItem.k8s }}"
      vault: "{{ organizationItem.vault }}"
      gitops: "{{ organizationItem.gitops }}"
      genesis: "{{ network.genesis }}"
    loop: "{{ network['organizations'] }}"
    loop_control:
      loop_var: organizationItem
    when: 
    - organizationItem.type == 'peer'
    - organizationItem.org_status is not defined or organizationItem.org_status == 'new'

  # Create and deploy Identities
  - name: 'Create Endorser Identities'
    include_role:
      name: setup/endorsers
    vars:
      organization: "{{ organizationItem.name | lower }}"
      component_ns: "{{ organizationItem.name | lower }}-ns"
      kubernetes: "{{ organizationItem.k8s }}"
      gitops: "{{ organizationItem.gitops }}"
      vault: "{{ organizationItem.vault }}"
      genesis: "{{ network.genesis }}"
    loop: "{{ network['organizations'] }}"
    loop_control:
      loop_var: organizationItem
    when: organizationItem.org_status is not defined or organizationItem.org_status == 'new'
