##############################################################################################
# This role creates the ledger txn value file for identities
##############################################################################################

##############################################################################################
# This tasks ensures the directory of crypto existance, if not exits it creates a new one
- name: Ensures {{ release_dir }}/{{ component_type }} dir exists
  include_role: 
    name: "{{ playbook_dir }}/../../shared/configuration/roles/check/setup"
  vars:
    path: "{{ release_dir }}/{{ component_type }}/"
    check: "ensure_dir" 

- name: Create HelmRelease file
  include_tasks: nested_main.yaml
  vars:
    identity_name: "{{ newIdentityName }}"
    admin_name: "{{ adminIdentityName }}"
    role: "{{ newIdentityRole }}"
