userpassword_networkmap: admin
mongodbPassword_networkmap: newdbnm
rootca: "{{playbook_dir}}/build/corda/cordarootca"
nmsca: "{{playbook_dir}}/build/corda/cordanetworkmap"
mongorootca: "{{playbook_dir}}/build/corda/mongorootca"
mongodbca: "{{playbook_dir}}/build/corda/mongodbca"
