apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "{{ $.Values.metadata.name }}"
  namespace: "{{ $.Values.metadata.namespace }}"
spec:
  serviceName: "{{ $.Values.metadata.name }}"
  replicas: 1
  selector:
    matchLabels:
      app: "{{ $.Values.metadata.name }}"
  template:
    metadata:
      labels:
        app: "{{ $.Values.metadata.name }}"
    spec:
      securityContext:
        fsGroup: 1000
      serviceAccountName: "{{ $.Values.vault.serviceAccountName }}"
      initContainers:
        - name:  "{{ $.Values.image.init.name }}"
          image:  "{{ $.Values.image.init.repository }}"
          imagePullPolicy: Always
          env:
            - name: VAULT_ADDR
              value: {{ $.Values.vault.address }}
            - name: VAULT_AUTH_PATH
              value: {{ $.Values.vault.authPath }}
            - name: VAULT_ROLE
              value: {{ $.Values.vault.role }}
          volumeMounts:
            - name: ebs-indy-webserver-keys
              mountPath: /keys
          command:
            - "sh"
            - "-c"
            - >
              apk update;
              apk add curl jq;

              validateVaultResponse () {
              if echo ${2} | grep "errors"; then
               echo "ERROR: unable to retrieve ${1}: ${2}"
               exit 1
               fi
              }

              KUBE_TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token);
              response=$(curl -s -o /dev/null -w "%{http_code}" $VAULT_ADDR/v1/sys/health);
              if [ $response != 200 ]; then
                exit 1
              fi

              curl --request POST --data '{"jwt": "'"$KUBE_TOKEN"'", "role": "'"$VAULT_ROLE"'"}' $VAULT_ADDR/v1/auth/$VAULT_AUTH_PATH/login | jq -j '.auth.client_token' > token;
              X_VAULT_TOKEN=$(cat token);

              LEDGER_SEED=$(curl --header "X-Vault-Token: $X_VAULT_TOKEN" $VAULT_ADDR/v1/"{{ $.Values.organization.name }}"/trustees/{{ $.Values.vault.trusteeName }}/identity/private | jq -r 'if .errors then . else . end');
              validateVaultResponse "secret ({{ $.Values.vault.trusteeName }}/identity/private)" "${LEDGER_SEED}";
              echo ${LEDGER_SEED} | jq -j ".data.seed" > /keys/seed;
              chmod 644 /keys/seed;

      containers:
        - name: "{{ $.Values.image.server.name }}"
          image: "{{ $.Values.image.server.repository }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: MAX_FETCH
              value: "50000"
            - name: RESYNC_TIME
              value: "120"
            - name: REGISTER_NEW_DIDS
              value: "True"
            - name: LEDGER_INSTANCE_NAME
              value: "BAF Sample App"
          volumeMounts:
            - name: {{ $.Values.organization.name }}-pool-transactions-genesis
              mountPath: /home/indy/ledger/sandbox/pool_transactions_genesis
              subPath: pool_transactions_genesis
            - name: ebs-indy-webserver-keys
              mountPath: /keys
          command:
          - "bash"
          - "-c"
          - >
            export LEDGER_SEED=$(cat /keys/seed);
            rm -rf /keys/seed;

            ./scripts/start_webserver.sh;
      imagePullSecrets:
        - name: "{{ $.Values.image.pullSecret }}"
      volumes:
        - name: {{ $.Values.organization.name }}-pool-transactions-genesis
          configMap:
            name: {{ $.Values.organization.name }}-ptg
  volumeClaimTemplates:
    - metadata:
        name: ebs-indy-webserver-keys
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "{{ $.Values.storage.className }}"
        resources:
          requests:
            storage: "{{ $.Values.storage.size }}"
