apiVersion: v1
appVersion: "2.0"
description: A Helm chart to deploy Indy WebServer for ability running of Identity demo where is needed endpoints which Indy WebServer is provided.
name: webserver
version: "1.0.0"
