#############################################################################################
# This role deletes the Vault configurations
#############################################################################################

#############################################################################################
# This task deletes the Docker credentials
- name: Delete docker creds
  k8s:
    kind: Secret
    namespace: "{{ org_namespace }}"
    name: "regcred"
    state: absent
    kubeconfig: "{{ kubernetes.config_file }}"
    context: "{{ kubernetes.context }}"
  ignore_errors: yes

- name: Delete Ambassador creds
  k8s:
    kind: Secret
    namespace: default
    name: "{{ peer.name }}-ambassador-certs"
    kubeconfig: "{{ kubernetes.config_file }}"
    context: "{{ kubernetes.context }}"
    state: absent
  loop: "{{ services.peers }}"
  loop_control:
    loop_var: peer
  ignore_errors: yes

# This task deletes vault auth
- name: Delete vault-auth path
  shell: |
    vault delete sys/auth/quorum{{ org_name }}
  environment:
    VAULT_ADDR: "{{ item.vault.url }}"
    VAULT_TOKEN: "{{ item.vault.root_token }}"

# This task deletes crypto material
- name: Delete Crypto material 
  shell: |
    vault delete {{ item.vault.secret_path | default('secret') }}/{{ org_namespace }}/crypto/{{ peer.name }}/transaction
    vault delete {{ item.vault.secret_path | default('secret') }}/{{ org_namespace }}/crypto/{{ peer.name }}/quorum
    vault delete {{ item.vault.secret_path | default('secret') }}/{{ org_namespace }}/crypto/{{ peer.name }}/certs
    vault delete {{ item.vault.secret_path | default('secret') }}/{{ org_namespace }}/crypto/genesis
  loop: "{{ services.peers }}"
  environment:
    VAULT_ADDR: "{{ item.vault.url }}"
    VAULT_TOKEN: "{{ item.vault.root_token }}"
  loop_control:
    loop_var: peer
  ignore_errors: yes

  # This task deletes application crypto material
- name: Delete Application Crypto material 
  shell: |
    vault delete {{ item.vault.secret_path | default('secret') }}/{{ org_namespace }}/smartContracts/General
  loop: "{{ services.peers }}"
  environment:
    VAULT_ADDR: "{{ item.vault.url }}"
    VAULT_TOKEN: "{{ item.vault.root_token }}"
  loop_control:
    loop_var: peer
  ignore_errors: yes

# This task deletes vault policies
- name: Delete Access policies 
  shell: |
    vault policy delete vault-crypto-organization-{{ peer.name }}-ro
  loop: "{{ services.peers }}"
  environment:
    VAULT_ADDR: "{{ item.vault.url }}"
    VAULT_TOKEN: "{{ item.vault.root_token }}"
  loop_control:
    loop_var: peer
  ignore_errors: yes
