---
- name: Converge
  hosts: localhost
  connection: local
  vars:
    network:
      docker:
        url: "test_url"
        username: "test_username"
        password: "test_password"
      env:
        retry_count: 30
        proxy: haproxy
    kubernetes: 
      config_file: "/tmp/molecule/kind-default/kubeconfig"
      context: "kind"
    item:
      vault:
        url: http://localhost:9090/
        root_token: root
      services:
        ca:
          name: ca
          subject: "/C=GB/ST=London/L=London/O=Orderer/CN=ca.supplychain-net"
          type: ca
          grpc:
            port: 7054
        nms:
          name: networkmap
          subject: "CN=Network Map,OU=FRA,O=FRA,L=Berlin,C=DE"
          db_subject: "/C=US/ST=California/L=San Francisco/O=My Company Ltd/OU=DBA/CN=mongoDB"
          type: networkmap
          ports:
            servicePort: 8080
            targetPort: 8080
          tls: "on"

  pre_tasks:
    - name: Create temp roles dir folder
      file:
        path: "{{ playbook_dir }}/../../shared/configuration"
        state: directory

    - name: Copy the roles
      copy:
        src: "{{ playbook_dir }}/../../../../shared/configuration/roles"
        dest: "{{ playbook_dir }}/../../shared/configuration"
               
  tasks:
    - name: "Copy openssl.conf to molecule directory"                 # Copying openssl.conf to molecule playbook directory
      copy:
        src: "{{ playbook_dir }}/../../openssl.conf"
        dest: "{{ playbook_dir }}"

    - name: "Test setup/nms role"
      include_role:
        name: "configuration/roles/setup/nms"
      vars:
        auth_lists:
          stdout: "abc"
        vault_policy_result:
          failed: True
        root_certs:
          failed: True
        networkmap_certs:
          failed: True
        mongoCA_certs:
          failed: True
        mongodb_certs:
          failed: True
        ambassador_tls_certs:
          failed: True 
        nms_root_certs:
          failed: True
        services:
          nms:
            tls: "on"
            name: networkmap
            subject: "CN=Network Map,OU=FRA,O=FRA,L=Berlin,C=DE"
            db_subject: "/C=US/ST=California/L=San Francisco/O=My Company Ltd/OU=DBA/CN=mongoDB"
            ports:
              servicePort: 8080
              targetPort: 8080
          networkmap:
            name: testnetworkmap
            subject: "CN=Corda Networkmap CA,OU=DLT,O=DLT,L=Berlin,C=DE"
            db_subject: "/C=US/ST=California/L=San Francisco/O=My Company Ltd/OU=DBA/CN=mongoDB"
            type: networkmap
            ports:
              servicePort: 8080
              targetPort: 8080
            tls: "on"
        organisation: testsupplychain
        component_ns: "default"          # namespace where docker creds are checked only for testing
        gitops:
          git_url: test_git_ssh
          branch: test_branch
          chart_source: "charts"
          release_dir: configuration/molecule/networkmap/test
        vault:
          url: http://localhost:9090/
          root_token: root
        item:
          subject: "CN=DLT Root CA,OU=DLT,O=DLT,L=London,C=GB"
          external_url_suffix: test_url
          gitops:
            git_url: test_git_ssh
            branch: test_branch
            chart_source: test_chart_source
          cloud_provider: aws
