metadata:
  #Provide the namespace for organization's server
  #Eg. namespace: carrier-net
  namespace: 

server:
  #Provide the name of the server as per deployment yaml.
  #Eg. name: carrier
  name: 
  # Provide the port the api server will be accessible by internally: 20001
  port: 
  #Provide the localmspid for organization
  #Eg. localmspid: carrierMSP
  localmspid: 
  #Provide the image name for the server container: 
  #Eg: hyperledgerlabs/supply_chain_fabric/rest-server:latest
  image: 
  #Provide the username of the user accessing the fabric network:user1
  username: 
  #Provide the path to the user's cert: 
  #Eg. "/secret/tls/user1.cert"
  cert_path: 
  #Provide the path to the user's key:
  #Eg: "/secret/tls/user1.pem"
  key_path: 

storage:
  #Provide the storageclassname for server
  #Eg. storageclassname: default
  storageclassname: 
  #Provide the storagesize for storage class
  #Eg. storagesize: 512Mi
  storagesize: 

vault:
  #Provide the vault server address
  #Eg. vaultaddress: http://a14689c11ce2a11e9ad640a71d2dbd67-371732458.eu-central-1.elb.amazonaws.com:8200
  address: 
  #Eg. vaultrole: vault-role
  role: 
  #Provide the kubernetes auth backed configured in vault for CA deployment
  #Eg. authpath: carrier-net-auth
  authpath: 
  #Provide the value for vault secretprefix
  #Eg. secretprefix: secret/crypto/peerOrganizations/carrier-net
  secretprefix: 
  #Provide the serviceaccountname for vault
  #Eg. serviceaccountname: vault-auth
  serviceaccountname: 
  #Provide the imagesecretname for vault
  #Eg. imagesecretname: regcred
  imagesecretname: 
  #Provide the image name for the init container: hyperledgerlabs/alpine-utils:1.0
  image:

service:
  #Provide the servicetype for a server
  #Eg. servicetype: ClusterIP
  servicetype: 
  ports:
  #Specify the ports 
  #Eg. apiPort: 20001
  #Eg. targetPort: 8000
    apiPort: 
    targetPort: 

connection:
  # Provide the name of the peer from which MSP will be copied
  # Eg. peer: peer0.manufacturer-net 
  peer:
  # Provide the peer external or intenal address
  # Eg. peerAddress: peer0.manufacturer-net.blockchaincloudpoc.com 
  peerAddress:
  # Provide the peer external or intenal port
  # Eg. peer: 8443 
  peerPort:
  # Provide the orderer external or intenal address
  # Eg. peerAddress: orderer.supplychain-net.blockchaincloudpoc.com 
  ordererAddress:
  # Provide the orderer external or intenal port
  # Eg. peer: 8443 
  ordererPort: