# This tasks copy the genesis material to the vault
- name: Copy genesis to Vault
  shell: |
    vault kv put {{ vault.secret_path | default('secret') }}/{{ component_ns }}/crypto/genesis genesisfile="{{ genesis }}" 
  environment:
    VAULT_ADDR: "{{ vault.url }}"
    VAULT_TOKEN: "{{ vault.root_token }}"
  tags:
    molecule-idempotence-notest
